typography_spectrum: 0.12066151416002965
content_rating:
  adult: false
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.5786616428527465
  lightness: 0.09491109598741525
  saturation: 0.22402074936307081
  rhythmicContrast: 0.7294376686559344
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/eafbd416-7400-4072-9499-d2e06be8d4d0.png
  type: null
  appId: null
layout_spectrum: 0.05681293362032364
analytics:
  google: UA-73235101-1
  facebook: '1703321536657152'
  twitter: null
author:
  name: David Ryman
  email: Linux@davidryman.com
  url: 'https://s87607151.onlinehome.us/v2/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/20a6c71d-8252-4a51-a789-9f3721ec528f.jpg
name: David Ryman
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Get your Grid
    url: 'https://thegrid.io/#19416'
    type: external
  - name: Consulting
    url: 'http://jobs.davidryman.com'
    type: external
  - name: Version 2.0
    url: 'http://s87607151.onlinehome.us/v2/'
    type: external
  - name: Thingiverse
    url: 'http://www.thingiverse.com/davidryman/about'
    type: external
  - name: open it
    url: 'https://thegrid.ai/davidryman'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7b85c9d3-43da-4aab-9efd-1b26a9c231c7.jpg
title: David Ryman
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/9e91348b-ce34-4087-ad4a-feb08d1ee448.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/9e91348b-ce34-4087-ad4a-feb08d1ee448.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: iBase
purpose:
  - type: contact
    url: 'mailto:DavidRyman714@gmail.com'
    label: Contact me
  - type: external
    url: 'https://www.facebook.com/drdavidryman'
    label: Facebook drdavidryman
