layout_spectrum: 0.2826839264659303
typography_spectrum: 0.5104634211798853
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.9244557765969952
  lightness: 0.23288631288002773
  saturation: 0.8854272636079626
  rhythmicContrast: 0.22153095516062682
content_rating:
  adult: false
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/eafbd416-7400-4072-9499-d2e06be8d4d0.png
  type: null
  appId: null
analytics:
  google: UA-73235101-1
  facebook: '1703321536657152'
  twitter: null
author:
  name: David Ryman
  email: Linux@davidryman.com
  url: 'https://s87607151.onlinehome.us/v2/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/20a6c71d-8252-4a51-a789-9f3721ec528f.jpg
name: David Ryman
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Get your Grid
    url: 'https://thegrid.io/#19416'
    type: external
  - name: Consulting
    url: 'http://jobs.davidryman.com'
    type: external
  - name: Version 2.0
    url: 'http://s87607151.onlinehome.us/v2/'
    type: external
  - name: Thingiverse
    url: 'http://www.thingiverse.com/davidryman/about'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7b85c9d3-43da-4aab-9efd-1b26a9c231c7.jpg
title: David Ryman
purpose:
  - type: contact
    url: 'mailto:DavidRyman714@gmail.com'
    label: Contact me
  - type: external
    url: 'https://www.facebook.com/drdavidryman'
    label: Facebook drdavidryman
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/180f6ca3-8a6e-4c0e-be58-56a730f97773.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/180f6ca3-8a6e-4c0e-be58-56a730f97773.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: iBase
