layout_spectrum: 0.13800515793263912
typography_spectrum: 0.3226321842521429
color:
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
  brandStrength: 0.0899668806232512
  lightness: 0.17251486470922828
  saturation: 0.21076206071302295
  rhythmicContrast: 0.9491905991453677
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-73235101-1
  facebook: null
  twitter: null
name: David Ryman
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: David Ryman V2.0
    url: 'https://http://s87607151.onlinehome.us/v2/'
    type: external
  - name: Thingiverse
    url: 'http://www.thingiverse.com/davidryman/about'
    type: external
  - name: Consulting
    url: 'https://jobs.davidryman.com'
    type: external
favicon: null
title: What's Govna doing?
purpose:
  - type: contact
    url: 'mailto:DavidRyman714@gmail.com'
    label: Contact me
  - type: external
    url: 'https://www.facebook.com/drdavidryman'
    label: Facebook drdavidryman
