name: David Ryman
favicon: null
layout_spectrum: 0.89156
typography_spectrum: 1
title: "What's The Gov'na doing?"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#14100d'
    - '#48623b'
    - '#819f5f'
    - '#d7aeb2'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
