typography_spectrum: 0.05662
color:
  brandColors:
    - '#000200'
    - '#4e433f'
    - '#6f6e74'
    - '#888983'
    - '#c9d1e4'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24997
analytics:
  google: UA-73235101-1
  facebook: null
  twitter: null
name: David Ryman
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: David Ryman V2.0
    url: 'https://http://s87607151.onlinehome.us/v2/'
    type: external
  - name: Thingiverse
    url: 'http://www.thingiverse.com/davidryman/about'
    type: external
  - name: Consulting
    url: 'https://jobs.davidryman.com'
    type: external
favicon: null
title: What's Govna doing?
purpose:
  - type: contact
    url: 'mailto:DavidRyman714@gmail.com'
    label: Contact me
  - type: external
    url: 'https://www.facebook.com/drdavidryman'
    label: Facebook drdavidryman
