typography_spectrum: 0.7876978954300284
content_rating:
  adult: false
color:
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
  brandStrength: 0.0899668806232512
  lightness: 0.17251486470922828
  saturation: 0.21076206071302295
  rhythmicContrast: 0.9491905991453677
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/eafbd416-7400-4072-9499-d2e06be8d4d0.png
  type: null
  appId: null
layout_spectrum: 0.13800515793263912
analytics:
  google: UA-73235101-1
  facebook: null
  twitter: null
author:
  name: David Ryman
  email: Linux@davidryman.com
  url: 'https://s87607151.onlinehome.us/v2/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/20a6c71d-8252-4a51-a789-9f3721ec528f.jpg
name: David Ryman
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Consulting
    url: 'http://jobs.david.ryman.com'
    type: external
  - name: Thingiverse
    url: 'http://www.thingiverse.com/davidryman/about'
    type: external
  - name: Version 2.0
    url: 'http://s87607151.onlinehome.us/v2/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7b85c9d3-43da-4aab-9efd-1b26a9c231c7.jpg
title: I got an idea
purpose:
  - type: contact
    url: 'mailto:DavidRyman714@gmail.com'
    label: Contact me
  - type: external
    url: 'https://www.facebook.com/drdavidryman'
    label: Facebook drdavidryman
