name: David Ryman
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: "What's The Gov'na doing?"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000100'
    - '#c2c0b1'
    - '#4693e1'
    - '#3b4858'
    - '#c3f6fa'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
