name: David Ryman
favicon: null
layout_spectrum: 0.68125
typography_spectrum: 0.05662
title: "What's Govna doing?"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73235101-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000200'
    - '#4e433f'
    - '#6f6e74'
    - '#888983'
    - '#c9d1e4'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
