name: David Ryman
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: "What's The Gov'na doing?"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfffa'
    - '#080607'
    - '#c377b8'
    - '#efa896'
    - '#0036bc'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
